theme: jekyll-theme-slate
title: Lab 9
description: Create Learning Lab course/repo within your GitHub account, Practice exiting and returning to the course from course repo, Work through course through GitHub, Download completed course repo as deliverable
